package controllers;

import java.io.IOException;
import java.util.Optional;

import controlutility.AlertStyle;
import controlutility.AlertStyleImpl;
import controlutility.RWSettings;
import controlutility.RWSettingsImpl;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.ButtonType;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

/**
 * The Controller related to the home.fxml GUI.
 *
 */
public final class HomeController {
    private RWSettings rwSett;
    private AlertStyle alStyle;

    @FXML
    private AnchorPane rootPane;
    /**
     * @throws IOException */
    public void initialize() throws IOException  {
        this.rwSett = new RWSettingsImpl();
        this.alStyle = new AlertStyleImpl();
    }

    /** used to switch scene on the same stage. */
    private void switchScene(final Parent pane) {
        final Stage stage = (Stage) this.rootPane.getScene().getWindow();
        final Scene scene = new Scene(pane, stage.getScene().getWidth(), stage.getScene().getHeight());
        scene.getStylesheets().add(ClassLoader.getSystemResource("css/" + rwSett.getCss()).toExternalForm());
        stage.setScene(scene);
    }

    /**
     * The handler for the click event generated by the 'btPlayGame' button.
     * 
     * @param event
     *                  event caused by select btPlayGame button
     * @exception IOException
     *                            if an I/O error occurs.
     */
    @FXML
    public void btPlayGame(final ActionEvent event) throws IOException {
        event.consume();
        final Parent pane = FXMLLoader.load(ClassLoader.getSystemResource("layouts/playGame.fxml"));
        this.switchScene(pane);
    }

    /**
     * The handler for the click event generated by the 'btHowToPlay' button.
     * 
     * @param event
     *                  event caused by select btHowToPlay button
     * @exception IOException
     *                            if an I/O error occurs.
     */
    @FXML
    public void btHowToPlay(final ActionEvent event) throws IOException {
        event.consume();
        final Parent pane = FXMLLoader.load(ClassLoader.getSystemResource("layouts/howToPlay.fxml"));
        this.switchScene(pane);
    }

    /**
     * The handler for the click event generated by the 'btSettings' button.
     * 
     * @param event
     *                  event caused by select btSettings button
     * @exception IOException
     *                            if an I/O error occurs.
     */
    @FXML
    public void btSettings(final ActionEvent event) throws IOException {
        event.consume();
        final Parent pane = FXMLLoader.load(ClassLoader.getSystemResource("layouts/settings.fxml"));
        this.switchScene(pane);
    }

    /**
     * The handler for the click event generated by the 'btStatistics' button.
     * 
     * @param event
     *                  event caused by select btStatistics button
     * @exception IOException
     *                            if an I/O error occurs.
     */
    @FXML
    public void btStatistics(final ActionEvent event) throws IOException {
        event.consume();
        // TODO
    }

    /**
     * The handler for the click event generated by the 'exit' button.
     * 
     * @param event
     *                  event caused by select exit button
     * @throws IOException 
     */
    @FXML
    public void exit(final ActionEvent event) throws IOException {
        event.consume();
        final Alert alert = new Alert(AlertType.CONFIRMATION);
        alert.setTitle("Confirmation Dialog");
        alert.setContentText("Are you shure to exit?");
        alert.setHeaderText(null);
        this.alStyle.setStyle(alert);
        final Optional<ButtonType> result = alert.showAndWait();
        if (result.get() == ButtonType.OK) {
            Platform.exit();
            System.exit(0);
        }
    }

}
