package controllers;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

import controlutility.RWSettings;
import controlutility.RWSettingsImpl;
import controlutility.WriteCss;
import controlutility.WriteCssImpl;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.ColorPicker;
import javafx.scene.control.MenuButton;
import javafx.scene.control.MenuItem;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.paint.Color;
import javafx.stage.FileChooser;
import javafx.stage.FileChooser.ExtensionFilter;
/**
 * */

public final class SettingsController extends BackHomeController {
    private static final String SEPARATOR = System.getProperty("file.separator");
    private final String urlImgMine = "src" + SEPARATOR + "main" + SEPARATOR + "resources" + SEPARATOR + "image"
            + SEPARATOR + "mines" + SEPARATOR;
    private final String urlImgFlag = "src" + SEPARATOR + "main" + SEPARATOR + "resources" + SEPARATOR + "image"
            + SEPARATOR + "flags" + SEPARATOR;
    private final String urlSound = "src" + SEPARATOR + "main" + SEPARATOR + "resources" + SEPARATOR + "sound"
            + SEPARATOR;
    private Color firstColor;
    private Color secondColor;
    private WriteCss writeCss;
    private RWSettings rwSett;
    private Clip clip;


    @FXML
    private  Button btBackHome;

    @FXML
    private  ColorPicker colorPicker1;

    @FXML
    private  ColorPicker colorPicker2;

    @FXML
    private  Button btPreview;

    @FXML
    private  MenuButton mbtMines;

    @FXML
    private  MenuButton mbtFlags;

    @FXML
    private  MenuButton mbtSound;

    @FXML
    private  ImageView ivMines;

    @FXML
    private  ImageView ivFlags;

    /**
     * initialize fields.
     * 
     * @exception IOException
     *                            if an I/O error occurs.
     * @throws LineUnavailableException 
     */
    public void initialize() throws IOException, LineUnavailableException {
        this.clip = AudioSystem.getClip(); 
        this.rwSett = new RWSettingsImpl();
        this.writeCss = new WriteCssImpl(this.rwSett.getFirstColor(), this.rwSett.getSecondColor());
        this.firstColor = Color.web(this.rwSett.getFirstColor());
        this.secondColor = Color.web(this.rwSett.getSecondColor());
        this.createMenuButtonM();
        this.createMenuButtonF();
        this.createMenuButtonS();
        this.updateImgMines();
        this.updateImgFlag();
        this.updateBtPreview();
    }

    private final EventHandler<ActionEvent> selectMine = new EventHandler<ActionEvent>() {
        @Override
        public void handle(final ActionEvent e) {
            rwSett.setMines(((MenuItem) e.getSource()).getText());
            try {
                updateImgMines();
                } catch (FileNotFoundException e1) {
               e1.printStackTrace();
            }
        }
    };


    private final EventHandler<ActionEvent> selectFlag = new EventHandler<ActionEvent>() {
        @Override
        public void handle(final ActionEvent e) {
            rwSett.setFlags(((MenuItem) e.getSource()).getText());
            try {
                updateImgFlag();
                } catch (FileNotFoundException e1) {
               e1.printStackTrace();
            }
        }
    };

    private void createMenuButtonM() {
        try (Stream<Path> walk = Files.walk(Paths.get(urlImgMine))) {
            final List<String> result = walk.filter(Files::isRegularFile).map(x -> x.toString()).collect(Collectors.toList());
            for (final String s : result) {
                final String name = s.replace(urlImgMine, "");
                final MenuItem item = new MenuItem(name);
                this.mbtMines.getItems().add(item);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        this.mbtMines.getItems().forEach(e -> e.setOnAction(selectMine));
    }

    private void updateImgMines() throws FileNotFoundException {
        this.ivMines.setImage(new Image(new FileInputStream(this.urlImgMine + this.rwSett.getMines())));
        this.mbtMines.setText(this.rwSett.getMines());
    }
    /**
     * The handler for the click event generated by the 'btAddImgMines' button.
     * @param event event caused by choosing new mine image
     * @throws IOException 
     */
    @FXML
    public void btAddImgMines(final ActionEvent event) throws IOException {
        event.consume();
        final FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Select new mines image");
        fileChooser.getExtensionFilters().addAll(new ExtensionFilter("Image Files", "*.png", "*.jpg", "*.gif"));
        final File selectedFile = fileChooser.showOpenDialog(null);
        if (selectedFile != null) {
            final Path destination = Paths.get(this.urlImgMine + SEPARATOR + selectedFile.getName());
            Files.copy(selectedFile.toPath(), destination);
            this.rwSett.setMines(selectedFile.getName());
            this.mbtMines.getItems().clear(); 
            this.createMenuButtonM();
            this.updateImgMines();
        }
    }

    private void createMenuButtonF() {
        try (Stream<Path> walk = Files.walk(Paths.get(urlImgFlag))) {
            final List<String> result = walk.filter(Files::isRegularFile).map(x -> x.toString()).collect(Collectors.toList());
            for (final String s : result) {
                final String name = s.replace(urlImgFlag, "");
                final MenuItem item = new MenuItem(name);
                this.mbtFlags.getItems().add(item);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        this.mbtFlags.getItems().forEach(e -> e.setOnAction(selectFlag));
    }

    private void updateImgFlag() throws FileNotFoundException {
        this.ivFlags.setImage(new Image(new FileInputStream(this.urlImgFlag + this.rwSett.getFlags())));
        this.mbtFlags.setText(this.rwSett.getFlags());
    }
    /**
     * The handler for the click event generated by the 'btAddImgMines' button.
     * @param event event caused by choosing new mine image
     * @throws IOException 
     */
    @FXML
    public void btAddImgFlags(final ActionEvent event) throws IOException {
        event.consume();
        final FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Select new flag image");
        fileChooser.getExtensionFilters().addAll(new ExtensionFilter("Image Files", "*.png", "*.jpg", "*.gif"));
        final File selectedFile = fileChooser.showOpenDialog(null);
        if (selectedFile != null) {
            final Path destination = Paths.get(this.urlImgFlag + SEPARATOR + selectedFile.getName());
            Files.copy(selectedFile.toPath(), destination);
            this.rwSett.setFlags(selectedFile.getName());
            this.mbtFlags.getItems().clear(); 
            this.createMenuButtonF();
            this.updateImgFlag();
        }
    }

    private void updateBtPreview() {
        final String fc = this.convertColor(this.firstColor);
        final String sc = this.convertColor(this.secondColor);
        final String btStyle = "-fx-background-color: linear-gradient(#" + fc + ", #" + sc
                + "); -fx-background-radius: 30, 30, 29, 28;-fx-padding: 3px 10px 3px 10px;";
        this.btPreview.setStyle(btStyle);
    }

    /**
     * The handler for the click event generated by the 'colorPicker1' button.
     * @param event event caused by choosing color
     */
    @FXML
    public void colorPicker1(final ActionEvent event) {
        event.consume();
        this.firstColor = this.colorPicker1.getValue();
        this.updateBtPreview();
        this.writeCss.update(this.convertColor(this.firstColor), this.convertColor(this.secondColor));
        this.rwSett.setFirstColor(this.convertColor(this.firstColor));
    }

    /**
     * The handler for the click event generated by the 'colorPicker2' button.
     * @param event event caused by choosing color
     */
    @FXML
    public void colorPicker2(final ActionEvent event) {
        event.consume();
        this.secondColor = this.colorPicker2.getValue();
        this.updateBtPreview();
        this.writeCss.update(this.convertColor(this.firstColor), this.convertColor(this.secondColor));
        this.rwSett.setSecondColor(this.convertColor(this.secondColor));
    }

    private String convertColor(final Color col) {
        return col.toString().substring(2, 8);
    }

    private final EventHandler<ActionEvent> selectSound = new EventHandler<ActionEvent>() {
        @Override
        public void handle(final ActionEvent e) {
            rwSett.setSong(((MenuItem) e.getSource()).getText());
            mbtSound.setText(rwSett.getSong());
            final String path = urlSound + rwSett.getSong();
            try (AudioInputStream audioStream = AudioSystem.getAudioInputStream(new File(path).getAbsoluteFile())) {
                btStop();
                clip.open(audioStream);
                clip.start();
            } catch (IOException | LineUnavailableException | UnsupportedAudioFileException ex) {
                ex.printStackTrace();
            }
        }
    };


    private void createMenuButtonS() {
        try (Stream<Path> walk = Files.walk(Paths.get(urlSound))) {
            final List<String> result = walk.filter(Files::isRegularFile).map(x -> x.toString()).collect(Collectors.toList());
            for (final String s : result) {
                final String name = s.replace(urlSound, "");
                final MenuItem item = new MenuItem(name);
                this.mbtSound.getItems().add(item);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        this.mbtSound.getItems().forEach(e -> e.setOnAction(selectSound));
        this.mbtSound.setText(rwSett.getSong());
    }
    /**
     * The handler for the click event generated by the 'stop' button.
     */
    @FXML
    public void btStop() {
        if (clip.isOpen()) {
            clip.stop();
            clip.close();
        }
    }
}
